services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: open-news-outlet
  s3:
    image: minio/minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
    ports:
      - 9000:9000
      - 9001:9001
  cache:
    image: redis
    restart: always
    environment:
      REDIS_PASSWORD: development
    ports:
      - 6379:6379
